#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
picom &
dunst &
xrandr --output DP-2 --primary --mode 2560x1440 --rotate normal --rate 143.97 --output DP-0 --mode 3840x2160 --rotate left --rate 60 --scale 1x1
xinput set-prop "14" "libinput Accel Profile Enabled" 0 1 0
feh --bg-fill ~/Pictures/wallpapers/horiz/wallhaven-2y3x86.jpg --bg-fill ~/Pictures/wallpapers/vert/wallhaven-wemkqx.jpg

steamlib=/games/SteamLibrary    # path to your steamlibrary
mygames=$(ls $steamlib/steamapps/appmanifest_*.acf | sed 's/[^0-9]*//g')    # this sed command removes everything but the digits

for game in $mygames; do
    bspc rule -a steam_app_$game desktop=^10 state=fullscreen
done

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
xinput set-prop "14" "libinput Accel Profile Enabled" 0 1 0
